### ISSUE TITLE
Sublime quick preview corrupts connection status

### ISSUE THREAD

**Issue by moltob** [jep-project/jep-sublime#1]
In a JEP enabled directory, can be reproduced like this:
- Hit CTRL-P to find a file by name.
- Start typing the file name.

Sublime will open and close files very fast and in arbitrary order for preview. This corrupts the JEP connection status. User ends up with an existing but invalid connection. JEP support not available in this state.

**Comment by moltob** [comment]
Issue also surfaces when navigating between files quickly in the sidebar. Analysis shows the following reason:
1. User preview a file.
2. Sublime shows JEP-supported file for preview, i.e. it activates a corresponding view. Important to make issue appear: Must be the only (first) view with JEP support.
3. JEP frontend opens connection to backend and starts processing.
4. User switches to another file for preview.
5. Sublime very quickly closes the first view and then opens the second file for preview.
6.  JEP frontend gets the close event. As the view was the only one, the corresponding connection to the backend is closed. Since there is a corresponding protocol (shutdown message, socket goes down, threads are stopped, ...), this is done _asynchronously_. The connection is in state `DISCONNECTING`.
7. JEP frontend gets the open (second) view event. It queries its connection pool and find a matching connection and starts using it. But: The connection is still `DISCONNECTING`and will eventually be just disconnected and no longer functional.

So the issue is the overlapping disconnection protocol and the premature reuse of the connection to the backend.

This behavior is actually implemented in jep-python, not jep-sublime.

**Comment by sanastasiou** [comment]
Don't want to intrude here - but why is the connection being closed when there aren't any views ( files ) left open? Resources? I used to keep connections alive, so long the backend is alive.. But ofc I am not jep expert so I might be missing something here :)

**Comment by moltob** [comment]
@sanastasiou I removed closing it just now. Yes, I wanted to keep it clean and tidy, but this has other disdvantages, like looosing the parsed project information on the backend side if all connections are closed.

And actually: there is usually just one or very few connections anyway.

Thanks for the comment.
